/* ============================================================
 * Billie Jean Dance — 8 大舞步数据
 * keyframes: [时间, 姿态局部值, ease?]（其余值继承 BASE 站立姿态）
 * spin: 整体旋转（转身 / 前倾），origin 为 SVG 坐标旋转轴心
 * ============================================================ */
window.BJ_MOVES = [
  {
    id: 'moonwalk',
    en: 'The Moonwalk',
    cn: '太空步',
    icon: '🕴️',
    diff: 4,
    tags: ['传奇', '必学'],
    music: '现场版副歌后的间奏段（1983 Motown 25）',
    keyframes: [
      [0.0, { x: 0,  hipL: 0, kneeL: 0,  footL: 0,   hipR: 0, kneeR: 62, footR: -12, shL: 16, elL: 26, shR: -10, elR: 22, y: 0 }, 'power2.inOut'],
      [0.45, { x: -3, hipL: -5, kneeL: 48, footL: 14, hipR: 0, kneeR: 8,  footR: -6,  shL: 6,  elL: 14, shR: -20, elR: 14, y: -1 }, 'power2.inOut'],
      [0.9, { x: -6, hipL: 0, kneeL: 0,  footL: 0,   hipR: 0, kneeR: 58, footR: -12, shL: 18, elL: 22, shR: -8,  elR: 22, y: 0 }, 'power2.inOut'],
      [1.35, { x: -9, hipL: -5, kneeL: 44, footL: 12, hipR: 0, kneeR: 6,  footR: -6,  shL: 8,  elL: 12, shR: -18, elR: 14, y: -1 }, 'power2.inOut'],
      [1.8, { x: -12, hipL: 0, kneeL: 0,  footL: 0,   hipR: 0, kneeR: 60, footR: -12, shL: 16, elL: 26, shR: -10, elR: 22, y: 0 }, 'power2.inOut'],
      [2.4, { x: 0,  hipL: 0, kneeL: 0,  footL: 0,   hipR: 0, kneeR: 62, footR: -12, shL: 16, elL: 26, shR: -10, elR: 22, y: 0 }, 'power2.inOut'],
    ],
    steps: [
      '双脚并拢站立，重心压在前脚掌，脚后跟微微离地',
      '右脚后跟抬起，用脚尖贴地向后滑一小步，同时身体重心移到左脚',
      '右脚脚跟落下着地，顺势抬起左脚后跟，左脚脚尖向后滑',
      '左右交替：一只脚滑、一只脚支撑，滑步幅度小而匀速',
      '上身放松，肩膀微微摆动，眼睛看前方——千万别低头看脚',
    ],
    tips: [
      '前脚掌发力，脚跟只是"搭"在地上',
      '滑步越小越像"悬浮"，大跨步就露馅了',
      '重心转移要干脆：换脚的一瞬间完成',
      '先用 0.5× 慢速练节奏，再慢慢提速到 117 BPM',
    ],
    mistakes: [
      '脚抬太高，变成"倒着走"',
      '重心没转移，两腿一起僵住卡顿',
      '低头看脚，破坏整个悬浮感',
    ],
    fact: '1983 年 Motown 25 周年晚会上，MJ 在 Billie Jean 现场表演中途首次公开太空步，全场起立欢呼——这歌的现场版从此成了"必跳"。',
  },
  {
    id: 'toestand',
    en: 'Toe Stand',
    cn: '脚尖站立',
    icon: '🦶',
    diff: 2,
    tags: ['定格', '标志'],
    music: '副歌第 4 小节末尾，常用来"刹车"定格',
    keyframes: [
      [0.0, {}, 'power2.out'],
      [0.5, { y: -4, kneeL: 10, kneeR: 10, shL: 8, elL: 12, shR: -8, elR: 12 }, 'power2.out'],
      [0.9, { y: -24, footL: 32, footR: 32, kneeL: 0, kneeR: 0, shL: -6, elL: 6, shR: 165, elR: -20 }, 'power3.out'],
      [1.4, { y: -24, footL: 32, footR: 32, kneeL: 0, kneeR: 0, shL: -10, elL: 0, shR: 165, elR: -20, headTilt: -5 }, 'power1.inOut'],
      [2.2, { y: -20, footL: 26, footR: 26, kneeL: 0, kneeR: 0, shL: -6, elL: 6, shR: 150, elR: -15 }, 'power1.inOut'],
      [2.8, { y: 0, footL: 0, footR: 0, kneeL: 0, kneeR: 0, shL: 0, elL: 0, shR: 0, elR: 0, headTilt: 0 }, 'power2.inOut'],
    ],
    steps: [
      '站直，双脚并拢，核心轻轻收紧',
      '微屈膝盖"蓄力"，像弹簧压下去',
      '迅速踮起脚尖，整个人提起来，脚跟离地',
      '保持 2-3 拍：右手指天、左手微展，眼神上扬',
      '核心稳住，缓缓落下脚跟还原',
    ],
    tips: [
      '脚踝发力，膝盖微屈缓冲，别锁死',
      '核心收紧是平衡的关键',
      '手臂动作要跟着"起-定-落"走，画面才完整',
    ],
    mistakes: [
      '膝盖完全锁直，晃来晃去',
      '身体前倾太多，变成鞠躬',
    ],
    fact: '这是 MJ 的标志性定格姿势——副歌唱完一个乐句，脚尖一站、手指天空，全场就等这一刻。',
  },
  {
    id: 'sideglide',
    en: 'Side Glide',
    cn: '侧滑步',
    icon: '➡️',
    diff: 3,
    tags: ['连接步', '流畅'],
    music: '主歌段，边走边滑的过渡动作',
    keyframes: [
      [0.0, { x: 0, hipL: 6, hipR: 6, shL: 10, elL: 20, shR: -8, elR: 15 }, 'power2.inOut'],
      [0.45, { x: 8, hipL: -16, hipR: -6, kneeL: 30, y: -2, shL: 6, elL: 14, shR: -14, elR: 18 }, 'power2.inOut'],
      [0.9, { x: 14, hipL: 0, hipR: 0, kneeL: 0, y: 0, shL: 10, elL: 20, shR: -8, elR: 15 }, 'power2.inOut'],
      [1.4, { x: 10, hipL: 14, hipR: 6, kneeR: 30, y: -2, shL: -14, elL: 18, shR: 6, elR: 14 }, 'power2.inOut'],
      [1.85, { x: 0, hipL: 0, hipR: 0, kneeR: 0, y: 0, shL: 10, elL: 20, shR: -8, elR: 15 }, 'power2.inOut'],
      [2.6, { x: 0, hipL: 6, hipR: 6, shL: 10, elL: 20, shR: -8, elR: 15 }, 'power2.inOut'],
    ],
    steps: [
      '双脚并拢站立，膝盖微屈，像站在冰面上',
      '右脚向右侧贴地滑出一小步，脚底不离地',
      '左脚快速跟上并拢，重心跟随移动',
      '反向再来：左脚滑出、右脚跟上',
      '上半身保持稳定，眼神看向移动方向',
    ],
    tips: [
      '脚底全程"粘"在地上，禁止跳跃',
      '膝盖微屈，重心压低更稳',
      '滑完立刻接下一个动作，别顿住',
    ],
    mistakes: [
      '跳着走，变成了"兔子跳"',
      '上半身跟着左右晃，像喝醉了',
    ],
    fact: '侧滑是 Billie Jean 现场版里最常见的过渡步，几乎每个乐句之间都会滑一下。',
  },
  {
    id: 'spin',
    en: 'The Spin',
    cn: '转身 360°',
    icon: '🌀',
    diff: 4,
    tags: ['爆发', '耍帅'],
    music: '副歌第 5 拍起跳，转完正好接定格',
    spin: [
      { at: 0.6, to: 360, dur: 1.0, origin: '100 95', ease: 'power2.inOut' },
    ],
    keyframes: [
      [0.0, {}, 'power2.out'],
      [0.4, { hipR: 65, kneeR: 90, shL: 25, elL: 30, shR: -25, elR: 30, y: -2 }, 'power2.out'],
      [0.6, { hipR: 65, kneeR: 90, shL: 25, elL: 30, shR: -25, elR: 30, y: -2, headTilt: 6 }, 'power2.inOut'],
      [1.6, { hipR: 65, kneeR: 90, shL: 25, elL: 30, shR: -25, elR: 30, y: -2, headTilt: 6 }, 'power1.inOut'],
      [2.0, { hipR: 0, kneeR: 0, shL: 0, elL: 0, shR: 0, elR: 0, y: 0, headTilt: 0 }, 'power2.out'],
      [2.5, {}, 'power1.inOut'],
    ],
    steps: [
      '重心放左脚，右脚轻轻抬起、屈膝',
      '双臂展开保持平衡，像旋转的陀螺',
      '以左脚前脚掌为轴，身体转一整圈 360°',
      '眼睛盯住墙上一个点（spotting），转头比身体快',
      '右脚落地，立刻接一个定格姿势',
    ],
    tips: [
      'Spotting（盯点）是防晕的核心技巧',
      '转的时候核心收紧，别甩头',
      '转完一定要"钉"住一拍，才算帅',
    ],
    mistakes: [
      '转太多圈，节奏全乱',
      '低头转，落地直接晃倒',
    ],
    fact: 'MJ 的转身永远在"最响的那一拍"完成，转完就是一个脚尖定格——节奏感就是他的签名。',
  },
  {
    id: 'sidekick',
    en: 'Side Kick',
    cn: '侧踢',
    icon: '🦵',
    diff: 3,
    tags: ['高光', 'hee-hee'],
    music: '副歌"People always told me…"处常用踢腿加手指天',
    keyframes: [
      [0.0, {}, 'power2.out'],
      [0.5, { hipR: 42, kneeR: 72, y: -3, shR: 12, elR: 22, shL: -10, elL: 16 }, 'power2.out'],
      [1.0, { hipR: 82, kneeR: 0, y: -9, lean: -7, shR: 152, elR: -18, shL: -62, elL: -72, headTilt: 8 }, 'power3.out'],
      [1.55, { hipR: 82, kneeR: 0, y: -9, lean: -7, shR: 152, elR: -18, shL: -62, elL: -72, headTilt: 8 }, 'power1.inOut'],
      [2.1, { hipR: 42, kneeR: 72, y: -3, lean: 0, shR: 12, elR: 22, shL: -10, elL: 16, headTilt: 0 }, 'power2.out'],
      [2.6, {}, 'power2.out'],
    ],
    steps: [
      '站定，右腿屈膝向上抬起',
      '膝盖向外打开，小腿向外踢出、伸直',
      '踢到最高点定格一拍——身体微侧、右手指天',
      '小腿收回、膝盖落下，轻轻落地',
      '落地瞬间接下一个动作，别停',
    ],
    tips: [
      '踢的高度以"站得稳"为准，别硬够',
      '身体微微侧倾借力，但核心别松',
      '手臂反方向摆动，画面更舒展',
    ],
    mistakes: [
      '踢太高，整个人往后倒',
      '上身前倾弯腰，变成"鞠躬踢"',
    ],
    fact: '侧踢 + 手指天 + "Hee-hee"，是 MJ 现场最上镜的三连拍，摄影师最爱。',
  },
  {
    id: 'heeltoe',
    en: 'Heel-Toe Slide',
    cn: '脚跟脚尖滑动',
    icon: '👠',
    diff: 3,
    tags: ['脚法', '节奏'],
    music: '间奏段原地小碎步，跟着鼓点踩',
    keyframes: [
      [0.0, { footL: 0, footR: 0, y: 0 }, 'power2.inOut'],
      [0.3, { footR: 28, y: -7, kneeR: 14, shR: 14, elR: 22, shL: -12, elL: 16 }, 'power2.inOut'],
      [0.7, { footR: -24, y: -2, kneeR: 4, x: 2, shR: 8, elR: 14, shL: -8, elL: 12 }, 'power2.inOut'],
      [1.1, { footL: 28, y: -7, kneeL: 14, x: -2, shL: -12, elL: 16, shR: 14, elR: 22 }, 'power2.inOut'],
      [1.5, { footL: -24, y: -2, kneeL: 4, x: 0, shL: -8, elL: 12, shR: 8, elR: 14 }, 'power2.inOut'],
      [2.2, { footL: 0, footR: 0, y: 0, kneeL: 0, kneeR: 0 }, 'power2.inOut'],
    ],
    steps: [
      '双脚并拢，先练右脚：脚尖踮起',
      '脚跟压下的同时，整只脚向前滑出一小段',
      '换左脚：脚尖踮起、脚跟压下、向前滑',
      '左右交替，像原地小跑但脚始终不离地',
      '身体随节奏轻微起伏，手臂自然摆动',
    ],
    tips: [
      '踝关节放松，节奏均匀：一、哒、二、哒',
      '滑出去的是"脚跟碾地"的感觉',
      '先慢速找脚感，再贴住 117 BPM',
    ],
    mistakes: [
      '变成跳，脚离开地面',
      '节奏忽快忽慢，赶拍子',
    ],
    fact: '这个脚法练好了，太空步的"滑"感就有了——它是所有滑步的地基。',
  },
  {
    id: 'lean',
    en: 'The Lean',
    cn: '前倾 45°',
    icon: '🤸',
    diff: 5,
    tags: ['高风险', '进阶'],
    danger: true,
    music: 'Smooth Criminal 标志动作；Billie Jean 现场会小幅前倾',
    spin: [
      { at: 1.2, to: 40, dur: 1.1, origin: '100 186', ease: 'power2.inOut' },
      { at: 3.0, to: 0, dur: 0.6, origin: '100 186', ease: 'power2.out' },
    ],
    keyframes: [
      [0.0, {}, 'power2.out'],
      [0.8, { shL: -24, elL: 34, shR: 24, elR: 34, y: -2 }, 'power2.out'],
      [1.2, { shL: -24, elL: 34, shR: 24, elR: 34, y: -2 }, 'power1.inOut'],
      [2.4, { shL: -24, elL: 34, shR: 24, elR: 34, y: -2 }, 'power1.inOut'],
      [3.0, { shL: -16, elL: 24, shR: 16, elR: 24, y: -1 }, 'power2.out'],
      [3.6, {}, 'power2.out'],
    ],
    steps: [
      '双脚并拢，脚趾抓地，核心用力收紧',
      '双手自然展开，像走钢丝一样找平衡',
      '以脚踝为轴，身体保持笔直，整体向前倾',
      '倾到极限前停住，保持片刻',
      '核心发力，把自己"拉"回直立',
    ],
    tips: [
      '前倾是"整体直挺挺地倒"，不是弯腰折腹',
      '从 15°-20° 开始，量力而行',
      '跟腱和核心力量是前提，先练靠墙辅助',
    ],
    mistakes: [
      '弯腰撅屁股，练成"鞠躬"',
      '没有保护直接挑战 45°，容易受伤',
    ],
    fact: 'MJ 的 45° 前倾其实靠特制鞋底的钩子；Billie Jean 现场版他更多是小幅前倾+后仰的"不倒翁"效果。',
  },
  {
    id: 'hatpoint',
    en: 'Hat Flick & Point',
    cn: '抓帽甩帽 + 指点',
    icon: '🎩',
    diff: 2,
    tags: ['手势', '表演'],
    music: '副歌开头，抓帽甩帽之后指向镜头',
    keyframes: [
      [0.0, {}, 'power2.out'],
      [0.4, { shR: 118, elR: 46, y: -2, headTilt: 3 }, 'power2.out'],
      [0.8, { shR: 58, elR: -26, x: 4, lean: -8, headTilt: -4 }, 'power3.out'],
      [1.2, { shL: -118, elL: -58, shR: 42, elR: 8, x: 8, lean: -6, headTilt: 6 }, 'power2.out'],
      [1.7, { shL: -118, elL: -58, shR: 42, elR: 8, x: 8, lean: -6, headTilt: 6 }, 'power1.inOut'],
      [2.2, { shL: 0, elL: 0, shR: 0, elR: 0, x: 0, lean: 0, headTilt: 0 }, 'power2.out'],
    ],
    steps: [
      '右手上扬，抓住帽檐（想象手里有顶礼帽）',
      '手腕发力，把帽向侧后方"甩"出去',
      '身体顺势微转，视线跟着帽子走',
      '左手向前指出，指向镜头，定格一拍',
      '收手还原，进入下一个动作',
    ],
    tips: [
      '甩帽靠手腕，不是整条胳膊抡',
      '眼神跟手：手到哪，观众看到哪',
      '定格要干脆利落，越"咔"越帅',
    ],
    mistakes: [
      '动作拖泥带水，帽子"甩"不出去',
      '手指出去了，眼睛还在看别处',
    ],
    fact: '抓帽甩帽出自 Billie Jean 的 MV，MJ 在 MV 里一共甩了两次帽、指了三次镜头——每次都是全片高光。',
  },
];
